[project]
name = "homework-10-1"
version = "0.1.0"
description = ""
authors = [
    {name = "Alexkor"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv (>=1.1.1,<2.0.0)",
    "requests (>=2.32.4,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-cov = "^6.1.1"


[tool.poetry.group.lint.dependencies]
flake8 = "^7.2.0"
isort = "^6.0.1"
black = "^25.1.0"
mypy = "^1.15.0"

#[tool.pytest.ini_options]
#pythonpath = [
#    "."
#]
[tool.pytest.ini_options]
addopts = "--cov=src --cov-fail-under=80 --cov-report term-missing"


[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_also = [
    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self\\.debug",


    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",


    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",


    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
]